<template>
  <PageContainer title="环境监测" description="室外天气、空气质量与未来室内传感器按环境空间统一管理">
    <template #actions><el-button type="primary" :icon="Plus" @click="openCreate">新增环境空间</el-button></template>
    <el-alert :closable="false" type="info" title="室外数据由后端私有天气服务配置读取；未配置密钥时不会展示或生成模拟天气数据。天气和空气质量的实际空间精度以数据源说明为准，不等同于街道实测。" />
    <div v-loading="loading" class="space-grid">
      <el-empty v-if="!spaces.length" description="尚未配置环境空间" />
      <article v-for="space in spaces" :key="space.id" class="space-card">
        <div class="space-head"><div><h3>{{ space.name }}</h3><p>{{ space.address || '未填写地址' }}</p></div><el-tag :type="space.enabled ? 'success' : 'info'">{{ space.enabled ? '已启用' : '已停用' }}</el-tag></div>
        <el-descriptions :column="1" size="small"><el-descriptions-item label="定位">{{ coordinate(space) }}</el-descriptions-item><el-descriptions-item label="主播报小智">{{ space.primarySpeakerName || '暂未绑定' }}</el-descriptions-item><el-descriptions-item label="室外天气">{{ outdoor[space.id]?.weatherText || (space.outdoorSourceConfigured ? '暂无读数' : '未配置私有天气服务') }}</el-descriptions-item><el-descriptions-item label="温度 / 湿度">{{ metric(outdoor[space.id]?.temperature, '℃') }} / {{ metric(outdoor[space.id]?.humidity, '%') }}</el-descriptions-item><el-descriptions-item label="空气质量">AQI {{ outdoor[space.id]?.aqi ?? '-' }}{{ outdoor[space.id]?.primaryPollutant ? ` · ${outdoor[space.id]?.primaryPollutant}` : '' }}</el-descriptions-item><el-descriptions-item label="更新时间">{{ outdoor[space.id]?.observedAt || '-' }}</el-descriptions-item><el-descriptions-item label="室内设备">暂未接入（接口已预留）</el-descriptions-item></el-descriptions>
        <div class="card-actions"><el-button link type="primary" @click="openEdit(space)">编辑空间</el-button><el-button :loading="refreshing === space.id" :disabled="!space.outdoorSourceConfigured || space.latitude == null" link type="primary" @click="refresh(space.id)">刷新室外数据</el-button><el-button link type="danger" @click="remove(space.id)">删除</el-button></div>
        <div class="rule-area"><div class="rule-head"><strong>主动播报规则</strong><el-button link type="primary" @click="openRule(space.id)">新增规则</el-button></div><el-empty v-if="!rules[space.id]?.length" :image-size="36" description="尚未配置；不会自动播报" /><div v-for="rule in rules[space.id]" :key="rule.id" class="rule-row"><span>{{ rule.name }}：{{ rule.metric === 'aqi' ? 'AQI' : '温度' }} {{ rule.thresholdValue != null ? `≥ ${rule.thresholdValue}` : `变化 ≥ ${rule.changeValue}` }}，连续 {{ rule.consecutiveCount }} 次</span><el-button link type="danger" @click="removeRule(rule.id, space.id)">删除</el-button></div></div>
      </article>
    </div>
    <el-dialog v-model="dialogVisible" :title="editingId ? '编辑环境空间' : '新增环境空间'" width="520px"><el-form :model="form" label-width="100px"><el-form-item label="空间名称" required><el-input v-model="form.name" placeholder="如：家 / 客厅" /></el-form-item><el-form-item label="详细地址"><el-input v-model="form.address" placeholder="可填写到街道、门牌或房间" /></el-form-item><el-form-item label="纬度"><el-input-number v-model="form.latitude" :precision="6" :step="0.000001" class="full" /></el-form-item><el-form-item label="经度"><el-input-number v-model="form.longitude" :precision="6" :step="0.000001" class="full" /></el-form-item><el-form-item label="主播报小智"><el-select v-model="form.primarySpeakerDeviceId" clearable class="full"><el-option v-for="d in devices" :key="d.id" :value="d.id" :label="`${d.name} / ${d.deviceCode}`" /></el-select></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
    <el-dialog v-model="ruleDialog" title="新增主动播报规则" width="520px"><el-alert :closable="false" type="warning" title="只有私有 TTS 已启用、连续命中、且不处于静音时段和冷却期时才会播报。" /><el-form :model="ruleForm" label-width="110px" class="rule-form"><el-form-item label="规则名称" required><el-input v-model="ruleForm.name" /></el-form-item><el-form-item label="监测指标"><el-select v-model="ruleForm.metric" class="full"><el-option label="温度" value="temperature" /><el-option label="AQI" value="aqi" /></el-select></el-form-item><el-form-item label="绝对阈值"><el-input-number v-model="ruleForm.thresholdValue" :min="0" class="full" /></el-form-item><el-form-item label="变化幅度"><el-input-number v-model="ruleForm.changeValue" :min="0" class="full" /></el-form-item><el-form-item label="连续命中次数"><el-input-number v-model="ruleForm.consecutiveCount" :min="1" :max="10" class="full" /></el-form-item><el-form-item label="冷却（分钟）"><el-input-number v-model="ruleForm.cooldownMinutes" :min="1" :max="1440" class="full" /></el-form-item><el-form-item label="静音时段"><el-time-picker v-model="quietTimes" is-range format="HH:mm" value-format="HH:mm:ss" range-separator="至" start-placeholder="开始" end-placeholder="结束" /></el-form-item></el-form><template #footer><el-button @click="ruleDialog=false">取消</el-button><el-button type="primary" @click="saveRule">保存</el-button></template></el-dialog>
  </PageContainer>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { Plus } from '@element-plus/icons-vue'; import { ElMessage } from 'element-plus'; import PageContainer from '@/components/PageContainer.vue'; import { createEnvironmentSpace, createEnvironmentAnnouncementRule, deleteEnvironmentAnnouncementRule, deleteEnvironmentSpace, getEnvironmentAnnouncementRules, getEnvironmentOutdoor, getEnvironmentSpaces, refreshEnvironmentOutdoor, updateEnvironmentSpace } from '@/api/environment'; import { getDeviceList } from '@/api/devices'; import type { EnvironmentAnnouncementRule, EnvironmentOutdoorReading, EnvironmentSpace, EnvironmentSpacePayload } from '@/types/environment'; import type { Device } from '@/types/device';
const spaces=ref<EnvironmentSpace[]>([]), devices=ref<Device[]>([]), loading=ref(false), dialogVisible=ref(false), ruleDialog=ref(false), refreshing=ref<number>(), editingId=ref<number>(); const outdoor=ref<Record<number, EnvironmentOutdoorReading | null>>({}), rules=ref<Record<number,EnvironmentAnnouncementRule[]>>({}); const form=reactive<EnvironmentSpacePayload>({name:'',address:'',latitude:undefined,longitude:undefined,primarySpeakerDeviceId:undefined}); const ruleForm=reactive({spaceId:0,name:'',metric:'temperature' as 'temperature'|'aqi',thresholdValue:undefined as number|undefined,changeValue:undefined as number|undefined,consecutiveCount:2,cooldownMinutes:60,quietStart:'22:30:00',quietEnd:'07:30:00',enabled:true}); const quietTimes=ref<[string,string]>(['22:30:00','07:30:00']);
const coordinate=(s:EnvironmentSpace)=>s.latitude==null||s.longitude==null?'未填写（无法查询室外数据）':`${s.latitude}, ${s.longitude}`;
const metric=(value:number|undefined,unit:string)=>value==null?'-':`${value}${unit}`;
async function load(){loading.value=true;try{[spaces.value,devices.value]=await Promise.all([getEnvironmentSpaces(),getDeviceList({page:1,pageSize:100}).then(p=>p.records)]);outdoor.value=Object.fromEntries(await Promise.all(spaces.value.map(async s=>[s.id,await getEnvironmentOutdoor(s.id)] as const)));rules.value=Object.fromEntries(await Promise.all(spaces.value.map(async s=>[s.id,await getEnvironmentAnnouncementRules(s.id)] as const)))}finally{loading.value=false}}
async function refresh(id:number){refreshing.value=id;try{outdoor.value[id]=await refreshEnvironmentOutdoor(id);ElMessage.success('室外数据已刷新')}finally{refreshing.value=undefined}}
function openCreate(){editingId.value=undefined;Object.assign(form,{name:'',address:'',latitude:undefined,longitude:undefined,primarySpeakerDeviceId:undefined});dialogVisible.value=true}
function openEdit(space:EnvironmentSpace){editingId.value=space.id;Object.assign(form,{name:space.name,address:space.address||'',latitude:space.latitude,longitude:space.longitude,primarySpeakerDeviceId:space.primarySpeakerDeviceId,enabled:space.enabled});dialogVisible.value=true}
async function save(){if(!form.name.trim())return ElMessage.warning('请输入空间名称');if((form.latitude==null)!==(form.longitude==null))return ElMessage.warning('经纬度必须同时填写');if(editingId.value)await updateEnvironmentSpace(editingId.value,form);else await createEnvironmentSpace(form);dialogVisible.value=false;await load();ElMessage.success(editingId.value?'环境空间已更新':'环境空间已创建')}
async function remove(id:number){await deleteEnvironmentSpace(id);await load();ElMessage.success('环境空间已删除')};onMounted(load)
function openRule(spaceId:number){Object.assign(ruleForm,{spaceId,name:'',metric:'temperature',thresholdValue:undefined,changeValue:undefined,consecutiveCount:2,cooldownMinutes:60,quietStart:'22:30:00',quietEnd:'07:30:00',enabled:true});quietTimes.value=['22:30:00','07:30:00'];ruleDialog.value=true}
async function saveRule(){if(!ruleForm.name.trim())return ElMessage.warning('请输入规则名称');if(ruleForm.thresholdValue==null&&ruleForm.changeValue==null)return ElMessage.warning('请填写绝对阈值或变化幅度');ruleForm.quietStart=quietTimes.value[0];ruleForm.quietEnd=quietTimes.value[1];await createEnvironmentAnnouncementRule(ruleForm);ruleDialog.value=false;rules.value[ruleForm.spaceId]=await getEnvironmentAnnouncementRules(ruleForm.spaceId);ElMessage.success('播报规则已保存')}
async function removeRule(id:number,spaceId:number){await deleteEnvironmentAnnouncementRule(id);rules.value[spaceId]=await getEnvironmentAnnouncementRules(spaceId);ElMessage.success('播报规则已删除')}
</script>
<style scoped>.space-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:16px;margin-top:16px}.space-card{padding:16px;border:1px solid var(--app-border);border-radius:8px;background:#fff}.space-head,.rule-head,.rule-row{display:flex;justify-content:space-between;gap:12px}.space-head h3{margin:0}.space-head p{margin:6px 0 14px;color:var(--app-muted)}.card-actions{display:flex;justify-content:flex-end;margin-top:12px}.rule-area{border-top:1px solid var(--app-border);margin-top:12px;padding-top:10px}.rule-row{align-items:center;font-size:13px;margin-top:8px}.rule-form{margin-top:16px}.full{width:100%}</style>
